"""Builds and runs the XSOAR MCP server.

The tool set is generated by FastMCP from openapi/xsoar.generated.json (Palo Alto's own XSOAR
Swagger spec, converted to OpenAPI 3.0 by scripts/fetch_spec.py). Re-running the generator picks
up upstream API changes - this file shouldn't need to change for that.

XSOAR's schema uses plain, MCP-safe property names throughout, so no schema-sanitizing step is
needed here.
"""

from __future__ import annotations

import json
from importlib import resources

from dotenv import load_dotenv
from fastmcp import FastMCP
from fastmcp.server.providers.openapi.routing import MCPType, RouteMap

from .auth import build_http_client

SPEC_RESOURCE = resources.files("xsoar_mcp.openapi").joinpath("xsoar.generated.json")

# XSOAR's API is mostly POST-based even for read operations (e.g. searchIncidents,
# indicatorsSearch are POST, not GET), so HTTP method alone can't separate read from write here.
# Every method is mapped to TOOL (never RESOURCE) so all operations are callable; which specific
# tools are read-only vs. mutating is documented in README.md's tool table instead, for wiring
# into your MCP client's permission rules (e.g. Claude Code's permissions.allow/ask).
ROUTE_MAPS = [
    RouteMap(methods=["GET"], mcp_type=MCPType.TOOL),
    RouteMap(methods=["POST"], mcp_type=MCPType.TOOL),
    RouteMap(methods=["PUT"], mcp_type=MCPType.TOOL),
    RouteMap(methods=["DELETE"], mcp_type=MCPType.TOOL),
    RouteMap(methods=["PATCH"], mcp_type=MCPType.TOOL),
]


def build_server() -> FastMCP:
    load_dotenv()  # picks up .env in the current working directory, if present
    spec = json.loads(SPEC_RESOURCE.read_text())

    return FastMCP.from_openapi(
        openapi_spec=spec,
        client=build_http_client(),
        name="xsoar",
        route_maps=ROUTE_MAPS,
    )


def main() -> None:
    build_server().run()  # stdio transport by default - Claude Code spawns this as a subprocess


if __name__ == "__main__":
    main()
