"""Builds and runs the XSOAR MCP server.

The tool set is generated by FastMCP from openapi/xsoar.generated.json (Palo Alto's own XSOAR
Swagger spec, converted to OpenAPI 3.0 by scripts/fetch_spec.py). Re-running the generator picks
up upstream API changes - only toolsets.py needs updating when operations are added or renamed.

XSOAR's schema uses plain, MCP-safe property names throughout, so no schema-sanitizing step is
needed here.
"""

from __future__ import annotations

import json
import logging
from importlib import resources

from dotenv import load_dotenv
from fastmcp import FastMCP
from fastmcp.server.providers.openapi.routing import MCPType
from fastmcp.utilities.openapi.models import HTTPRoute
from mcp.types import ToolAnnotations

from .auth import build_http_client
from .toolsets import (
    CLASSIFICATION,
    TOOLSETS,
    classification_drift,
    describe_drift,
    enabled_toolsets,
    read_only_mode,
)

logger = logging.getLogger(__name__)

SPEC_RESOURCE = resources.files("xsoar_mcp.openapi").joinpath("xsoar.generated.json")


def build_server() -> FastMCP:
    load_dotenv()  # picks up .env in the current working directory, if present
    spec = json.loads(SPEC_RESOURCE.read_text())
    unclassified, stale = classification_drift(spec)
    if unclassified or stale:
        logger.warning(describe_drift(unclassified, stale))

    toolsets = enabled_toolsets()
    read_only = read_only_mode()
    all_toolsets = toolsets == TOOLSETS.keys()

    def classify(route: HTTPRoute) -> tuple[str | None, bool]:
        # An operation added upstream but not yet in toolsets.py is assumed to be a write.
        return CLASSIFICATION.get(route.operation_id, (None, False))

    # Every included operation becomes a TOOL (never a RESOURCE), since XSOAR uses POST for many
    # reads and method can't distinguish them. Excluded operations are never registered at all,
    # so read-only mode and the toolset filter also hold against calls by name.
    def route_map_fn(route: HTTPRoute, _default: MCPType) -> MCPType:
        toolset, is_read = classify(route)
        if read_only and not is_read:
            return MCPType.EXCLUDE
        if toolset not in toolsets and not (toolset is None and all_toolsets):
            return MCPType.EXCLUDE
        return MCPType.TOOL

    def mcp_component_fn(route: HTTPRoute, component) -> None:
        toolset, is_read = classify(route)
        component.tags |= {toolset or "unclassified", "read" if is_read else "write"}
        component.annotations = ToolAnnotations(read_only_hint=is_read)

    return FastMCP.from_openapi(
        openapi_spec=spec,
        client=build_http_client(),
        name="xsoar",
        route_map_fn=route_map_fn,
        mcp_component_fn=mcp_component_fn,
    )


def main() -> None:
    build_server().run()  # stdio transport by default - Claude Code spawns this as a subprocess


if __name__ == "__main__":
    main()
